[project]
name = "practice-topic-2-db"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.40",
]
